//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PE_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoAcademico
    {
        public CursoAcademico()
        {
            this.Alumno = new HashSet<Alumno>();
            this.Modulo = new HashSet<Modulo>();
            this.Detalle_Alumno = new HashSet<Detalle_Alumno>();
        }
    
        public int idCA { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Alumno> Alumno { get; set; }
        public virtual ICollection<Modulo> Modulo { get; set; }
        public virtual ICollection<Detalle_Alumno> Detalle_Alumno { get; set; }
    }
}
