//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PE_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Alumno
    {
        public int idDetA { get; set; }
        public int carnet { get; set; }
        public int idCa { get; set; }
        public string porcentajeAsistencia { get; set; }
        public string estado { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual CursoAcademico CursoAcademico { get; set; }
    }
}
