//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PE_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluacion
    {
        public Evaluacion()
        {
            this.Detalle_Nota = new HashSet<Detalle_Nota>();
        }
    
        public int idEv { get; set; }
        public string evaluacion1 { get; set; }
        public int idPon { get; set; }
    
        public virtual ICollection<Detalle_Nota> Detalle_Nota { get; set; }
        public virtual Ponderaciones Ponderaciones { get; set; }
    }
}
