//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_PE_2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ponderaciones
    {
        public Ponderaciones()
        {
            this.Evaluacion = new HashSet<Evaluacion>();
        }
    
        public int idPon { get; set; }
        public decimal ponderacion { get; set; }
    
        public virtual ICollection<Evaluacion> Evaluacion { get; set; }
    }
}
